# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc983fbbcc56589ac8022168a6b838bdb4cad72ae080a1dc2dc76cee53ddea061351521c99803f6b6045ba6b4fed4afb5dbdb315055c55df7e39b7ec63702dd1

test:
  secret_key_base: 4d136b90e677024b880f59895276b57c0da07b6af86dd530123bc65c2aba91ca845611cd9bfc27c677fc0eaf7e3e56946cea82fbaac8f769271f57c0edca0c48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
